# src/dashboard_v2.py
import html as _html
from datetime import datetime

HTML = """<!doctype html>
<html lang="en">
<meta charset="utf-8"/>
<title>Owlume — Dashboard v2</title>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<style>
 body{{font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Arial,sans-serif;padding:24px;max-width:1100px;margin:0 auto;}}
 h1{{margin:0 0 6px;}}
 .meta{{color:#666;margin-bottom:18px;}}
 .grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:16px 0;}}
 .card{{border:1px solid #ddd;border-radius:12px;padding:16px;box-shadow:0 1px 6px rgba(0,0,0,.05);}}
 .kpi{{font-size:32px;font-weight:700}}
 .mono{{font-family:ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size:12px;}}
 table{{width:100%;border-collapse:collapse;}}
 th,td{{border-bottom:1px solid #eee;padding:6px 8px;text-align:left;}}
 .evt{{white-space:nowrap; overflow:hidden; text-overflow:ellipsis;}}
</style>
<body>
  <h1>🦉 Owlume — Dashboard v2</h1>
  <div class="meta">Last updated: {updated_at}</div>

  <div class="grid">
    <div class="card">
      <div>Clarity Δ (avg)</div>
      <div class="kpi">{avg_delta}</div>
      <div class="meta">{samples} samples</div>
    </div>
    <div class="card">
      <div>Empathy activation</div>
      <div class="kpi">{empathy_rate}%</div>
      <div class="meta">{emp_samples} samples</div>
    </div>
    <div class="card">
      <div>Events processed</div>
      <div class="kpi">{events}</div>
      <div class="meta">Top cell: {top_cell}</div>
    </div>
  </div>

  <div class="card">
    <h3>Top Cells</h3>
    <table>
      <thead><tr><th>Mode × Principle</th><th>Count</th></tr></thead>
      <tbody>
        {top_rows}
      </tbody>
    </table>
  </div>

  <div class="card">
    <h3>Recent Feedback Events</h3>
    <table>
      <thead><tr><th>Time</th><th>DID</th><th>Type</th><th>Δ</th><th>Cell</th></tr></thead>
      <tbody>
        {event_rows}
      </tbody>
    </table>
  </div>

  <div class="meta mono">Generated by T5-S7</div>
</body>
</html>
"""

def _fmt(n):
    try:
        return f"{float(n):.3f}"
    except Exception:
        return "0.000"

def render_dashboard_v2(aggregates: dict, recent_events: list[dict]) -> str:
    ag = aggregates or {}
    counts = (ag.get("counts") or {})
    clarity = (ag.get("clarity") or {})
    empathy = (ag.get("empathy") or {})
    top_cells = (ag.get("top_cells") or {})

    top_sorted = sorted(top_cells.items(), key=lambda kv: kv[1], reverse=True)
    top_cell = f"{top_sorted[0][0]} ({top_sorted[0][1]})" if top_sorted else "—"

    top_rows = "\n".join(
        f"<tr><td>{_html.escape(k)}</td><td>{v}</td></tr>"
        for k, v in top_sorted[:10]
    )

    def evt_row(e):
        ts = e.get("timestamp", "—")
        did = e.get("did", "—")
        et = e.get("type", "EVENT")
        d = e.get("cg_delta", "—")
        cell = "—"
        if e.get("mode") and e.get("principle"):
            cell = f'{e["mode"]} × {e["principle"]}'
        return (
            f"<tr>"
            f"<td class='evt'>{_html.escape(ts)}</td>"
            f"<td>{_html.escape(did)}</td>"
            f"<td>{_html.escape(et)}</td>"
            f"<td>{_html.escape(str(d))}</td>"
            f"<td>{_html.escape(cell)}</td>"
            f"</tr>"
        )

    event_rows = "\n".join(evt_row(e) for e in recent_events[-20:])

    return HTML.format(
        updated_at=_html.escape((ag.get("meta") or {}).get("updated_at", "—")),
        avg_delta=_fmt(clarity.get("avg_delta", 0.0)),
        samples=int(clarity.get("samples", 0)),
        empathy_rate=f"{round(float(empathy.get('activation_rate', 0.0))*100, 1)}",
        emp_samples=int(empathy.get("samples", 0)),
        events=int(counts.get("events", 0)),
        top_cell=_html.escape(top_cell),
        top_rows=top_rows or "<tr><td colspan='2'>—</td></tr>",
        event_rows=event_rows or "<tr><td colspan='5'>No recent events</td></tr>",
    )
