name: Owlume Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    name: Run smoke tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps (best effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install jsonschema
          fi

      - name: Validate schemas (quick gate)
        run: python -u scripts/validate_schemas.py --strict

      - name: Run engine smoke test (if present)
        run: |
          if [ -f scripts/smoke_test_engine_fusion.py ]; then
            echo "Running scripts/smoke_test_engine_fusion.py"
            python -u scripts/smoke_test_engine_fusion.py
          else
            echo "::notice ::No smoke test script found at scripts/smoke_test_engine_fusion.py (skipping)."
          fi
